# Generated by Django 6.0.5 on 2026-10-01 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0001_initial'),
        ('pharmacies', '0005_alter_ville_options_pharmacie_localite_libre_and_more'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adresse_livraison',
            field=models.TextField(blank=True, help_text='Pré-remplie par le patient si besoin_livraison = True. La pharmacie peut modifier avant création de la livraison.', null=True, verbose_name='Adresse de livraison souhaitée'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='besoin_livraison',
            field=models.BooleanField(default=False, help_text='Si coché : la pharmacie organisera une livraison après paiement des médicaments. Le client paie la livraison au livreur.', verbose_name='Besoin de livraison à domicile'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_livraison',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone contact pour la livraison'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'statut'], name='reservation_user_id_8a67ed_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['pharmacie', 'statut'], name='reservation_pharmac_7f8902_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['besoin_livraison'], name='reservation_besoin__5e8a30_idx'),
        ),
    ]
