# Generated by Django 6.0.5 on 2026-10-01 03:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='adresse_livraison',
            field=models.TextField(blank=True, help_text='Adresse complète où livrer les médicaments (indication : porte, bâtiment, repère GPS...).', null=True, verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='contact_client',
            field=models.CharField(blank=True, help_text='Souvent différent du profil, pour un proche à qui on livre.', max_length=30, null=True, verbose_name='Téléphone du client pour la livraison'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='livree_a',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison effective'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='methode_paiement_livraison',
            field=models.CharField(choices=[('especes', 'Espèces (cash au livreur)'), ('orange_money', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('wave', 'Wave')], default='especes', help_text='Le client paie la livraison au livreur par ce moyen.', max_length=30, verbose_name='Méthode de paiement de la livraison'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='montant_livraison',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prix que le client paie au livreur (ex: 500 FCFA).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant de la livraison (FCFA)'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='statut_paiement_livraison',
            field=models.CharField(choices=[('en_attente', 'En attente (à payer au livreur)'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', help_text="Devient « Payé » quand le livreur confirme avoir reçu l'argent.", max_length=30, verbose_name='Statut du paiement de la livraison'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude (position livreur)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude (position livreur)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_cours', max_length=20, verbose_name='Statut de la livraison'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['livreur', 'statut'], name='deliveries_livreur_921c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['statut_paiement_livraison'], name='deliveries_statut__76f3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['reservation'], name='deliveries_reserva_17212b_idx'),
        ),
    ]
