# Generated by Django 6.0.5 on 2026-09-08 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(blank=True, null=True, verbose_name='Entrée utilisateur')),
                ('input_audio', models.FileField(blank=True, null=True, upload_to='ai/audio_inputs/', verbose_name="Audio d'entrée")),
                ('output', models.TextField(blank=True, null=True, verbose_name='Réponse du système')),
                ('output_audio', models.FileField(blank=True, null=True, upload_to='ai/audio_outputs/', verbose_name='Audio de réponse')),
                ('type', models.CharField(choices=[('search', 'Recherche médicament'), ('symptom', 'Recherche par symptôme'), ('general', 'Question générale')], default='general', max_length=20, verbose_name='Type de recherche')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Contexte de recherche')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Interaction IA',
                'verbose_name_plural': 'Interactions IA',
                'db_table': 'ai_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
