# Generated by Django 5.2.6 on 2026-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='input_audio',
            field=models.FileField(blank=True, null=True, upload_to='ai/audio_inputs/', verbose_name="Audio d'entrée"),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='output_audio',
            field=models.FileField(blank=True, null=True, upload_to='ai/audio_outputs/', verbose_name='Audio de réponse'),
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='input',
            field=models.TextField(blank=True, null=True, verbose_name='Entrée utilisateur'),
        ),
        migrations.AlterField(
            model_name='aiinteraction',
            name='output',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse du système'),
        ),
    ]
