# Generated by Django 6.0.5 on 2026-07-13 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_add_pharmacie_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacie',
            options={'ordering': ['nom'], 'verbose_name': 'Pharmacie', 'verbose_name_plural': 'Pharmacies'},
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='adresse',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='commune',
            field=models.CharField(help_text="Quartier ou secteur (ex. Cocody à Abidjan, centre-ville à M'batto).", max_length=100, verbose_name='Commune / quartier'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='nom',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom de la pharmacie'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
    ]
