# Generated by Django 6.0.5 on 2026-10-01 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_alter_pharmacie_options_alter_pharmacie_adresse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ville',
            options={'ordering': ['type', 'nom'], 'verbose_name': 'Localité (ville / commune / village)', 'verbose_name_plural': 'Localités (villes / communes / villages)'},
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='localite_libre',
            field=models.CharField(blank=True, help_text="Si votre village/commune n'est pas dans la liste déroulante du dessus : écrivez son nom ici (ex: Village Tiébissou, Kouto, Danané).", max_length=150, null=True, verbose_name='Localité (texte libre)'),
        ),
        migrations.AddField(
            model_name='ville',
            name='population',
            field=models.PositiveIntegerField(blank=True, help_text='Optionnel, utile pour prioriser les zones.', null=True, verbose_name='Population approximative'),
        ),
        migrations.AddField(
            model_name='ville',
            name='type',
            field=models.CharField(choices=[('ville', 'Ville'), ('commune', 'Commune'), ('village', 'Village')], default='ville', help_text='Permet de distinguer les grandes villes des communes et villages.', max_length=20, verbose_name='Type de localité'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='commune',
            field=models.CharField(help_text="Précision dans la localité (ex: Cocody à Abidjan, centre-ville à M'batto, marché du village).", max_length=100, verbose_name='Commune / quartier / secteur'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='ville',
            field=models.ForeignKey(blank=True, help_text='Choisissez dans la liste si votre localité existe. Sinon, laissez vide et remplissez le champ « Localité (texte libre) » ci-dessous.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to='pharmacies.ville', verbose_name='Localité (ville / commune / village)'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='nom',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nom de la localité'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['type', 'is_active'], name='villes_type_c42cea_idx'),
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['region', 'type'], name='villes_region_5bdafc_idx'),
        ),
    ]
