# Generated by Django 6.0.5 on 2026-07-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0001_initial'),
        ('pharmacies', '0004_alter_pharmacie_options_alter_pharmacie_adresse_and_more'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['pharmacie'], name='stocks_pharmac_b6ce58_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['medicament'], name='stocks_medicam_e8dc1d_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['date_mise_a_jour'], name='stocks_date_mi_2fb8b5_idx'),
        ),
    ]
