# Generated by Django 6.0.5 on 2026-10-01 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0001_initial'),
        ('pharmacies', '0004_alter_pharmacie_options_alter_pharmacie_adresse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='medicaments_extraits',
            field=models.JSONField(blank=True, help_text="Médicaments et quantités détectés sur l'ordonnance (OCR ou saisie manuelle). Format : [{nom, dosage, quantite}]", null=True, verbose_name='Médicaments extraits'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='pharmacie',
            field=models.ForeignKey(blank=True, help_text='La pharmacie choisie par le patient (souvent la moins chère).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='pharmacies.pharmacie', verbose_name='Pharmacie chargée du traitement'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Commentaire du pharmacien lors de la validation ou du refus.', null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['pharmacie', 'statut'], name='ordonnances_pharmac_8f9e17_idx'),
        ),
        migrations.AddIndex(
            model_name='ordonnance',
            index=models.Index(fields=['user', 'statut'], name='ordonnances_user_id_c5a997_idx'),
        ),
    ]
