# Generated by Django 6.0.5 on 2026-10-01 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_adresse_livraison_delivery_contact_client_and_more'),
        ('payments', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery',
            field=models.ForeignKey(blank=True, help_text='Requis pour un paiement de livraison.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='deliveries.delivery', verbose_name='Livraison concernée'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'encaissement"),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_mobile_money',
            field=models.CharField(blank=True, help_text='Identifiant de la transaction renvoyé par Orange Money / MTN / Wave.', max_length=255, null=True, verbose_name='Référence transaction Mobile Money'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type_paiement',
            field=models.CharField(choices=[('medicaments', 'Paiement des médicaments → Pharmacie'), ('livraison', 'Paiement de la livraison → Livreur')], default='medicaments', help_text="Détermine à qui revient l'argent : pharmacie (médicaments) ou livreur (livraison).", max_length=30, verbose_name='Type de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='methode',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn', 'MTN Mobile Money'), ('wave', 'Wave'), ('carte', 'Carte Bancaire'), ('especes', 'Espèces (cash)')], max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Requis pour un paiement de médicaments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation', verbose_name='Réservation concernée'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['type_paiement', 'statut'], name='payments_type_pa_524fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reservation'], name='payments_reserva_5bfdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['delivery'], name='payments_deliver_da81a3_idx'),
        ),
    ]
